### ISSUE TITLE
Tensorflow light_curve_analysis AttributeError

### ISSUE THREAD

**Issue by bfhealy** [nuclear-multimessenger-astronomy/nmma#112]
This `get_model` call in `model.py` raises the error below. If I replace `self.svd_mag_model.keys()` with `filters=filters` in the line below (and in line 246), the code runs.

https://github.com/nuclear-multimessenger-astronomy/nmma/blob/f90e39b70ced584bfee6dd997185efe065e17f38/nmma/em/model.py#L235

```
light_curve_analysis --model Bu2022Ye --interpolation_type tensorflow --outdir outdir --label injection --prior priors/Bu2022Ye.prior --tmin 0.1 --tmax 20 --dt 0.5 --error-budget 1 --nlive 512 --Ebv-max 0 --injection ./injection.json --injection-num 0 --injection-outfile outdir/lc.csv --generation-seed 42 --filters u,g,r,i,z,y,J,H,K --plot --remove-nondetections --svd-path ./svdmodels_2022_16348_dropout0.6
Install afterglowpy if you want to simulate afterglows.
Install wrapt_timeout_decorator if you want timeout simulations.
Creating light curve model for inference
Traceback (most recent call last):
  File "/Users/bhealy/miniforge3/envs/nmma_api2/bin/light_curve_analysis", line 33, in <module>
    sys.exit(load_entry_point('nmma==0.0.8', 'console_scripts', 'light_curve_analysis')())
  File "/Users/bhealy/nmma/nmma/em/analysis.py", line 428, in main
    model_names, models, light_curve_model = create_light_curve_model_from_args(
  File "/Users/bhealy/nmma/nmma/em/analysis.py", line 398, in create_light_curve_model_from_args
    lc_model = SVDLightCurveModel(**lc_kwargs)
  File "/Users/bhealy/nmma/nmma/em/model.py", line 235, in __init__
    get_model(self.svd_path, f"{self.model}_tf", self.svd_mag_model.keys())
AttributeError: 'SVDLightCurveModel' object has no attribute 'svd_mag_model'
```

**Comment by mcoughlin** [comment]
@bfhealy please fix anything for TF path. I have been focused on sklearn.
