### ISSUE TITLE
svdmodel_benchmark multiprocessing

### ISSUE THREAD

**Issue by mcoughlin** [nuclear-multimessenger-astronomy/nmma#125]
Running 

svdmodel_benchmark --model Bu2019lm --svd-path svdmodels_bns --interpolation-type sklearn_gp --data-path lcs_bns/

I get:

Benchmarking model Bu2019lm on filter ['ps1__i', 'ztfi', 'uvot__uvw2', 'ps1__y', 'ps1__r', 'uvot__u', 'bessellr', 'ps1__g', 'uvot__uvm2', 'atlasc', 'bessellux', '2massj', '2massks', 'bessellv', 'sdssu', 'ps1__z', 'uvot__b', 'uvot__white', 'atlaso', 'bessellb', '2massh', 'ztfg', 'ztfr', 'besselli', 'uvot__uvw1', 'uvot__v'] with 4 cpus
  0%|                                                  | 0/1596 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/bin/svdmodel_benchmark", line 33, in <module>
    sys.exit(load_entry_point('nmma==0.0.11', 'console_scripts', 'svdmodel_benchmark')())
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/lib/python3.9/site-packages/nmma-0.0.11-py3.9.egg/nmma/em/svdmodel_benchmark.py", line 175, in main
    chi2_dict_array = p_map(chi2_func, grid_entry_names, num_cpus=args.ncpus)
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/lib/python3.9/site-packages/p_tqdm-1.4.0-py3.9.egg/p_tqdm/p_tqdm.py", line 65, in p_map
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/lib/python3.9/site-packages/p_tqdm-1.4.0-py3.9.egg/p_tqdm/p_tqdm.py", line 54, in _parallel
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/lib/python3.9/site-packages/multiprocess-0.70.14-py3.9.egg/multiprocess/pool.py", line 748, in next
    raise value
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/lib/python3.9/site-packages/multiprocess-0.70.14-py3.9.egg/multiprocess/pool.py", line 431, in _handle_tasks
    put(task)
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/lib/python3.9/site-packages/multiprocess-0.70.14-py3.9.egg/multiprocess/connection.py", line 209, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/mcoughlin/opt/anaconda3/envs/nmma/lib/python3.9/site-packages/multiprocess-0.70.14-py3.9.egg/multiprocess/connection.py", line 396, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

I have fixed the code to turn off multi-processing if ncpus = 1, but unsure if there is a way to lower the memory requirement (which I think is the issue). Maybe doing it filter by filter?

**Comment by tsunhopang** [comment]
Looking into it now

**Comment by mcoughlin** [comment]
@tsunhopang Did you figure anything out here?

**Comment by tsunhopang** [comment]
Not yet, as my run just keep getting struck but without the error message.
