### ISSUE TITLE
light_curve_analysis Python 3.8 Compatibility

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#146]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
light_curve_analysis fails to run on a python 3.8 environment

**To Reproduce**
1. Install NMMA on a 3.8 environment
2. Run command 
`light_curve_analysis --model Bu2019lm --svd-path ./svdmodels --interpolation_type tensorflow --outdir outdir --label injection --prior priors/Bu2019lm.prior --tmin 0.1 --tmax 20 --dt 0.5 --error-budget 1 --nlive 512 --Ebv-max 0 --trigger-time 59397.28347219899 --data example_files/candidate_data/ZTF20abwysqy.dat --plot`
3. See error

**Expected behavior**
standard light_curve_analysis output

**Screenshots**

**Platform information:**
 - NMMA version: commit 7688594ef7e5b21136d221610344d3705aaaa876
 - Platform: unknown

**Additional context**
Full Error Output:

```
WARNING: AstropyDeprecationWarning: The update_default_config function is deprecated and may be removed in a future version. [sncosmo]
2023-07-12 13:36:51.026434: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-12 13:36:51.032211: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-12 13:36:51.074604: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-12 13:36:51.075674: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-12 13:36:51.901093: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
13:36 bilby INFO    : Running for label 'injection', output will be saved to 'outdir'
13:36 bilby INFO    : Analysis priors:
13:36 bilby INFO    : luminosity_distance=Uniform(minimum=0.0, maximum=200.0, name='luminosity_distance', latex_label='$D_L$', unit=None, boundary=None)
13:36 bilby INFO    : KNphi=Uniform(minimum=15.0, maximum=75.0, name='KNphi', latex_label='$\\Phi$', unit=None, boundary=None)
13:36 bilby INFO    : inclination_EM=Sine(minimum=0.0, maximum=1.5707963267948966, name='inclination_EM', latex_label='$\\iota$', unit=None, boundary=None)
13:36 bilby INFO    : KNtimeshift=Uniform(minimum=-2.0, maximum=1.0, name='trigger_time', latex_label='$t_0$', unit=None, boundary=None)
13:36 bilby INFO    : log10_mej_dyn=Uniform(minimum=-3.0, maximum=-1.0, name='log10_mej_dyn', latex_label='$\\log_{10}M^{\\rm{dyn}}_{\\rm{ej}}$', unit=None, boundary=None)
13:36 bilby INFO    : log10_mej_wind=Uniform(minimum=-3.0, maximum=-0.5, name='log10_mej_wind', latex_label='$\\log_{10}M^{\\rm{wind}}_{\\rm{ej}}$', unit=None, boundary=None)
13:36 bilby INFO    : Ebv=0.0
13:36 bilby INFO    : Analysis likelihood class: <class 'nmma.em.likelihood.OpticalLightCurve'>
13:36 bilby INFO    : Analysis likelihood noise evidence: 0.0
13:36 bilby WARNING : Supplied argument 'queue_size' not an argument of 'Pymultinest', removing.
13:36 bilby WARNING : Supplied argument 'check_point_delta_t' not an argument of 'Pymultinest', removing.
13:36 bilby WARNING : Using cached result
13:36 bilby INFO    : Summary of results:
nsamples: 3143
ln_noise_evidence:  0.000
ln_evidence: -25.602 +/-  0.130
ln_bayes_factor: -25.602 +/-  0.130

13:36 bilby INFO    : Writing samples file to /home/nvanbemmel/KNTraP/model_fitting/nmma/outdir/injection_posterior_samples.dat
Traceback (most recent call last):
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/bin/light_curve_analysis", line 33, in <module>
    sys.exit(load_entry_point('nmma==0.0.8', 'console_scripts', 'light_curve_analysis')())
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/nmma-0.0.8-py3.8.egg/nmma/em/analysis.py", line 659, in main
    result.plot_corner()
  File "/home/nvanbemmel/.local/lib/python3.8/site-packages/bilby/core/utils/plotting.py", line 65, in wrapper_decorator
    return func(*args, **kwargs)
  File "/home/nvanbemmel/.local/lib/python3.8/site-packages/bilby/core/result.py", line 1114, in plot_corner
    import corner
  File "/home/nvanbemmel/.local/lib/python3.8/site-packages/corner/__init__.py", line 6, in <module>
    from .corner import corner
  File "/home/nvanbemmel/.local/lib/python3.8/site-packages/corner/corner.py", line 12, in <module>
    from .arviz_corner import arviz_corner
  File "/home/nvanbemmel/.local/lib/python3.8/site-packages/corner/arviz_corner.py", line 9, in <module>
    from arviz.data import convert_to_dataset
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/arviz-0.15.1-py3.8.egg/arviz/__init__.py", line 33, in <module>
    from .data import *
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/arviz-0.15.1-py3.8.egg/arviz/data/__init__.py", line 2, in <module>
    from .base import CoordSpec, DimSpec, dict_to_dataset, numpy_to_data_array
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/arviz-0.15.1-py3.8.egg/arviz/data/base.py", line 11, in <module>
    import xarray as xr
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/xarray-2023.4.2-py3.8.egg/xarray/__init__.py", line 1, in <module>
    from xarray import testing, tutorial
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/xarray-2023.4.2-py3.8.egg/xarray/testing.py", line 10, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/xarray-2023.4.2-py3.8.egg/xarray/core/duck_array_ops.py", line 34, in <module>
    from xarray.core import dask_array_ops, dtypes, nputils
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/xarray-2023.4.2-py3.8.egg/xarray/core/dask_array_ops.py", line 7, in <module>
    from xarray.core import dtypes, nputils
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/xarray-2023.4.2-py3.8.egg/xarray/core/dtypes.py", line 7, in <module>
    from xarray.core import utils
  File "/home/nvanbemmel/anaconda3/envs/nmma_env/lib/python3.8/site-packages/xarray-2023.4.2-py3.8.egg/xarray/core/utils.py", line 443, in <module>
    class Frozen(Mapping[K, V]):
TypeError: 'ABCMeta' object is not subscriptable
```

**Comment by tylerbarna** [comment]
User encountering this issue was able to resolve it by switching to a python 3.9 environment for install. Progress of NMMA development may be such that Python 3.8 may not be supported in the future.
