### ISSUE TITLE
potential missing dependency

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#166]
**Describe the bug**

**To Reproduce**
1. Fresh environment on 3.9
2. follow quickstart guide, but install nmma with `pip install .`
3. Run the quickstart injection and lightcurve analysis commands (though I changed the model to nugent-hyper for speed of testing) but add the `bestfit` and/or `plot` flags to `light_curve_analysis` command

**Expected behavior**
completes and outputs a plot and besfit json in addition to standard output files

**Platform information:**
 - NMMA version: current commit
 - Platform: WSL

**Additional context**
Commands:
`(nmma_dev) tbarna@SurfaceLaptopStudio:~/nmma$ nmma_create_injection --prior-file priors/Me2017.prior --eos-file example_files/eos/ALF2.dat --binary-type BNS --n-injection 100 --original-parameters --extension json`

`(nmma_dev) tbarna@SurfaceLaptopStudio:~/nmma$ light_curve_analysis --mode
l nugent-hyper  --outdir outdir --label injection --prior priors/nugent-hyper.prior --tmin 0.1 --tmax 20 --dt 0.5 --error-budget 1 --nlive 512 --E
bv-max 0 --injection ./injection.json --injection-num 0 --injection-outfi
le outdir/lc.csv --generation-seed 42 --filters u,g,r,i,z,y,J,H,K --plot 
--remove-nondetections --bestfit`

Output error (occurs after completion of sampling):
```
12:13 bilby INFO    : Overwriting outdir/pm_injection/ with /tmp/tmplf_grhxp/
 ln(ev)=  -334.92928230590724      +/-  0.11991422050591682     
 Total Likelihood Evaluations:         9427
 Sampling finished. Exiting MultiNest
  analysing data from /tmp/tmplf_grhxp/.txt
12:13 bilby INFO    : Overwriting outdir/pm_injection/ with /tmp/tmplf_grhxp/
12:13 bilby INFO    : Sampling time: 0:06:42.884648
12:13 bilby INFO    : Summary of results:
nsamples: 2366
ln_noise_evidence:  0.000
ln_evidence: -334.929 +/-  0.120
ln_bayes_factor: -334.929 +/-  0.120

12:13 bilby INFO    : Writing samples file to /home/tbarna/nmma/outdir/injection_posterior_samples.dat
Traceback (most recent call last):
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/arviz/__init__.py", line 322, in <module>
    import colorcet
ModuleNotFoundError: No module named 'colorcet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tbarna/anaconda3/envs/nmma_dev/bin/light_curve_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/nmma/em/analysis.py", line 672, in main
    result.plot_corner(parameters=injection)
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/bilby/core/utils/plotting.py", line 65, in wrapper_decorator
    return func(*args, **kwargs)
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/bilby/core/result.py", line 1173, in plot_corner
    import corner
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/corner/__init__.py", line 6, in <module>
    from corner.corner import corner
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/corner/corner.py", line 12, in <module>
    from corner.arviz_corner import arviz_corner
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/corner/arviz_corner.py", line 9, in <module>
    from arviz.data import convert_to_dataset
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/arviz/__init__.py", line 324, in <module>
    _mpl_cm("gray", _linear_grey_10_95_c0)
  File "/home/tbarna/anaconda3/envs/nmma_dev/lib/python3.9/site-packages/arviz/__init__.py", line 318, in _mpl_cm
    mpl.colormaps.register(cmap, name="cet_" + name)
AttributeError: module 'matplotlib' has no attribute 'colormaps'
```

**Comment by tylerbarna** [comment]
fixed by running `pip install colorcet` and then re-running lightcurve analysis

seems like colorcet might be missing from the dependencies @mcoughlin

**Comment by mcoughlin** [comment]
@tylerbarna Just pushing 0.0.18 with this dependency.
