### ISSUE TITLE
File move/deletion errors for multiprocessing lightcurve-analysis

### ISSUE THREAD

**Issue by bfhealy** [nuclear-multimessenger-astronomy/nmma#316]
Running a multiprocessing `lightcurve-analysis` produces errors related to deleting/moving files at the end of the run, probably because the files were already changed by the time the additional processes tried to find them. These errors do not interfere with the data/plots produced by the code, but they do make slurm status emails report a failed job when running on a cluster.

Example call:

```
mpiexec -np 10 lightcurve-analysis --model Bu2023Ye --interpolation-type tensorflow --svd-path svdmodels_Bu2023Ye --Ebv-max 0.0 --outdir output_gw170817_uniform --label AT2017gfo --trigger-time 57982.5285236896 --data example_files/lightcurves/AT2017gfo.dat --prior priors/Bu2023Ye.prior --error-budget 1.0 --filters sdssu,ps1__g,ps1__r,ps1__i,ps1__z,ps1__y,2massj,2massh,2massks --plot --local-only
```

Errors:
```
Traceback (most recent call last):
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/shutil.py", line 816, in move
Traceback (most recent call last):
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'outdir/ZTF21abdpqpq_pymultinest_result.json' -> 'outdir/ZTF21abdpqpq_pymultinest_result.json.old'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhealy/.conda/envs/nmma_env/bin/lightcurve-analysis", line 8, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'outdir/ZTF21abdpqpq_pymultinest_result.json' -> 'outdir/ZTF21abdpqpq_pymultinest_result.json.old'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhealy/.conda/envs/nmma_env/bin/lightcurve-analysis", line 8, in <module>
    sys.exit(main())
    sys.exit(main())
  File "/expanse/lustre/projects/umn131/bhealy/nmma/nmma/em/analysis.py", line 926, in main
  File "/expanse/lustre/projects/umn131/bhealy/nmma/nmma/em/analysis.py", line 926, in main
    analysis(args)
  File "/expanse/lustre/projects/umn131/bhealy/nmma/nmma/em/analysis.py", line 670, in analysis
    analysis(args)
  File "/expanse/lustre/projects/umn131/bhealy/nmma/nmma/em/analysis.py", line 670, in analysis
    result = bilby.run_sampler(
    result = bilby.run_sampler(
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/site-packages/bilby/core/sampler/__init__.py", line 262, in run_sampler
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/site-packages/bilby/core/sampler/__init__.py", line 262, in run_sampler
    result.save_to_file(extension=save, gzip=gzip, outdir=outdir)
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/site-packages/bilby/core/result.py", line 783, in save_to_file
    result.save_to_file(extension=save, gzip=gzip, outdir=outdir)
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/site-packages/bilby/core/result.py", line 783, in save_to_file
    move_old_file(filename, overwrite)
    move_old_file(filename, overwrite)
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/site-packages/bilby/core/utils/io.py", line 411, in move_old_file
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/site-packages/bilby/core/utils/io.py", line 411, in move_old_file
    shutil.move(filename, filename + ".old")
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/shutil.py", line 837, in move
    shutil.move(filename, filename + ".old")
    os.unlink(src)
FileNotFoundError: [Errno 2] No such file or directory: 'outdir/ZTF21abdpqpq_pymultinest_result.json'
  File "/home/bhealy/.conda/envs/nmma_env/lib/python3.10/shutil.py", line 837, in move
    os.unlink(src)
FileNotFoundError: [Errno 2] No such file or directory: 'outdir/ZTF21abdpqpq_pymultinest_result.json'
```

**Comment by bfhealy** [comment]
This issue appears to be fixed by a recent commit.
